const sqlite = @import("sqlite");

// https://www.sqlite.org/rescode.html
pub fn parseResultCode(code: i32) ErrorCodes!OkCodes {
    return switch (code) {
        sqlite.SQLITE_OK => OkCodes.ok,
        sqlite.SQLITE_ERROR => ErrorCodes.Err,
        sqlite.SQLITE_INTERNAL => ErrorCodes.Internal,
        sqlite.SQLITE_PERM => ErrorCodes.Perm,
        sqlite.SQLITE_ABORT => ErrorCodes.Abort,
        sqlite.SQLITE_BUSY => ErrorCodes.Busy,
        sqlite.SQLITE_LOCKED => ErrorCodes.Locked,
        sqlite.SQLITE_NOMEM => ErrorCodes.NoMem,
        sqlite.SQLITE_READONLY => ErrorCodes.Readonly,
        sqlite.SQLITE_INTERRUPT => ErrorCodes.Interrupt,
        sqlite.SQLITE_IOERR => ErrorCodes.IoErr,
        sqlite.SQLITE_CORRUPT => ErrorCodes.Corrupt,
        sqlite.SQLITE_NOTFOUND => ErrorCodes.NotFound,
        sqlite.SQLITE_FULL => ErrorCodes.Full,
        sqlite.SQLITE_CANTOPEN => ErrorCodes.CantOpen,
        sqlite.SQLITE_PROTOCOL => ErrorCodes.Protocol,
        sqlite.SQLITE_EMPTY => ErrorCodes.Empty,
        sqlite.SQLITE_SCHEMA => ErrorCodes.Schema,
        sqlite.SQLITE_TOOBIG => ErrorCodes.TooBig,
        sqlite.SQLITE_CONSTRAINT => ErrorCodes.Constrain,
        sqlite.SQLITE_MISMATCH => ErrorCodes.Mismatch,
        sqlite.SQLITE_MISUSE => ErrorCodes.Misuse,
        sqlite.SQLITE_NOLFS => ErrorCodes.NoLfs,
        sqlite.SQLITE_AUTH => ErrorCodes.Auth,
        sqlite.SQLITE_FORMAT => ErrorCodes.Format,
        sqlite.SQLITE_RANGE => ErrorCodes.Range,
        sqlite.SQLITE_NOTADB => ErrorCodes.NotADB,
        sqlite.SQLITE_NOTICE => ErrorCodes.Notice,
        sqlite.SQLITE_WARNING => ErrorCodes.Warning,
        sqlite.SQLITE_ROW => OkCodes.row,
        sqlite.SQLITE_DONE => OkCodes.done,
        else => unreachable,
    };
}

pub const OkCodes = enum(u8) {
    ok = sqlite.SQLITE_OK,
    row = sqlite.SQLITE_ROW,
    done = sqlite.SQLITE_DONE,
};

pub const ErrorCodes = error{
    Err,
    Internal,
    Perm,
    Abort,
    Busy,
    Locked,
    NoMem,
    Readonly,
    Interrupt,
    IoErr,
    Corrupt,
    NotFound,
    Full,
    CantOpen,
    Protocol,
    Empty,
    Schema,
    TooBig,
    Constrain,
    Mismatch,
    Misuse,
    NoLfs,
    Auth,
    Format,
    Range,
    NotADB,
    Notice,
    Warning,
};
